//Test automatically generated by display_test_generator.py
let URL = "http://localhost:3000/wayland"; //PUT_URL_OF_TEST_SITE_HERE 
describe("Ensures content matches page at http://localhost:3000/Test-Site", () => {
	it("Ensures contents and styles match", () => {
		cy.visit(URL);
		cy.wait(5000);
	}),
	it("Ensures the 1th p tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('p').eq(0);
	}),
	it("Ensures the 2th p tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('p').eq(1);
	}),
	it("Ensures the 3th p tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('p').eq(2);
	}),
	it("Ensures the 4th p tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('p').eq(3);
	}),
	it("Ensures the 5th p tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('p').eq(4);
	}),
	it("Ensures the 6th p tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('p').eq(5);
	}),
	it("Ensures the 7th p tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('p').eq(6)
			.should('have.css', 'font-size', '15px')
			.should('have.css', 'color', 'rgb(40, 40, 40)');
	}),
	it("Ensures the 8th p tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('p').eq(7)
			.should('have.css', 'font-size', '15px')
			.should('have.css', 'color', 'rgb(40, 40, 40)');
	}),
	it("Ensures the 9th p tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('p').eq(8);
	}),
	it("Ensures the 10th p tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('p').eq(9);
	}),
	it("Ensures the 11th p tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('p').eq(10)
			.should('have.css', 'font-size', '12px');
	}),
	it("Ensures the 1th h3 tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('h3').eq(0)
			.should('have.css', 'font-size', '20px');
	}),
	it("Ensures the 1th h4 tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('h4').eq(0);
	}),
	it("Ensures the 2th h4 tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('h4').eq(1)
			.should('have.css', 'color', 'rgb(47, 79, 79)');
	}),
	it("Ensures the 3th h4 tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('h4').eq(2)
			.should('have.css', 'color', 'rgb(47, 79, 79)');
	}),
	it("Ensures the 4th h4 tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('h4').eq(3)
			.should('have.css', 'color', 'rgb(47, 79, 79)');
	}),
	it("Ensures the 5th h4 tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('h4').eq(4)
			.should('have.css', 'color', 'rgb(47, 79, 79)');
	}),
	it("Ensures the 6th h4 tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('h4').eq(5)
			.should('have.css', 'font-size', '20px');
	}),
	it("Ensures the 1th nav tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('nav').eq(0)
			.should('have.css', 'height', '104px')
			.should('have.css', 'min-height', '90px')
			.should('have.css', 'position', 'fixed')
			.should('have.css', 'width', '1200px')
			.should('have.css', 'background-image', 'none')
			.should('have.css', 'background-position-x', '0%')
			.should('have.css', 'background-position-y', '0%')
			.should('have.css', 'background-size', 'auto')
			.should('have.css', 'background-repeat-x', 'initial')
			.should('have.css', 'background-repeat-y', 'initial')
			.should('have.css', 'background-attachment', 'scroll')
			.should('have.css', 'background-origin', 'padding-box')
			.should('have.css', 'background-clip', 'border-box')
			.should('have.css', 'background-color', 'rgba(255, 255, 255, 1)');
	}),
	it("Ensures the 2th nav tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('nav').eq(1)
			.should('have.css', 'display', 'flex')
			.should('have.css', 'padding-top', '30px')
			.should('have.css', 'padding-right', '0px')
			.should('have.css', 'padding-bottom', '30px')
			.should('have.css', 'padding-left', '0px')
			.should('have.css', 'flex-grow', '1');
	}),
	it("Ensures the 1th img tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('img').eq(0)
			.should('have.css', 'display', 'inline-block');
	}),
	it("Ensures the 2th img tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('img').eq(1)
			.should('have.css', 'height', '300px')
			.should('have.css', 'width', '400px')
			.should('have.css', 'object-fit', 'cover');
	}),
	it("Ensures the 3th img tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('img').eq(2)
			.should('have.css', 'height', '300px')
			.should('have.css', 'width', '400px')
			.should('have.css', 'object-fit', 'cover');
	}),
	it("Ensures the 4th img tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('img').eq(3)
			.should('have.css', 'height', '300px')
			.should('have.css', 'width', '400px')
			.should('have.css', 'object-fit', 'cover');
	}),
	it("Ensures the 5th img tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('img').eq(4);
	}),
	it("Ensures the 6th img tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('img').eq(5);
	}),
	it("Ensures the 7th img tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('img').eq(6)
			.should('have.css', 'display', 'inline-block');
	}),
	it("Ensures the 1th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(0);
	}),
	it("Ensures the 2th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(1);
	}),
	it("Ensures the 3th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(2);
	}),
	it("Ensures the 4th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(3);
	}),
	it("Ensures the 5th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(4);
	}),
	it("Ensures the 6th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(5);
	}),
	it("Ensures the 7th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(6);
	}),
	it("Ensures the 8th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(7)
			.should('have.css', 'width', '244px')
			.should('have.css', 'height', '221px');
	}),
	it("Ensures the 9th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(8)
			.should('have.css', 'width', '244px')
			.should('have.css', 'height', '221px');
	}),
	it("Ensures the 10th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(9)
			.should('have.css', 'width', '244px')
			.should('have.css', 'height', '221px');
	}),
	it("Ensures the 11th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(10)
			.should('have.css', 'width', '244px')
			.should('have.css', 'height', '221px');
	}),
	it("Ensures the 12th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(11)
			.should('have.css', 'margin-top', '20px');
	}),
	it("Ensures the 13th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(12)
			.should('have.css', 'color', 'rgb(0, 0, 0)')
			.should('have.css', 'padding-top', '0px')
			.should('have.css', 'padding-right', '0px')
			.should('have.css', 'padding-bottom', '0px')
			.should('have.css', 'padding-left', '0px')
			.should('have.css', 'position', 'relative')
			.should('have.css', 'border-top-left-radius', '15px')
			.should('have.css', 'border-top-right-radius', '15px')
			.should('have.css', 'border-bottom-right-radius', '15px')
			.should('have.css', 'border-bottom-left-radius', '15px');
	}),
	it("Ensures the 14th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(13)
			.should('have.css', 'color', 'rgb(0, 0, 0)')
			.should('have.css', 'padding-top', '0px')
			.should('have.css', 'padding-right', '0px')
			.should('have.css', 'padding-bottom', '0px')
			.should('have.css', 'padding-left', '0px')
			.should('have.css', 'position', 'relative')
			.should('have.css', 'border-top-left-radius', '15px')
			.should('have.css', 'border-top-right-radius', '15px')
			.should('have.css', 'border-bottom-right-radius', '15px')
			.should('have.css', 'border-bottom-left-radius', '15px');
	}),
	it("Ensures the 15th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(14);
	}),
	it("Ensures the 16th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(15);
	}),
	it("Ensures the 17th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(16);
	}),
	it("Ensures the 18th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(17);
	}),
	it("Ensures the 19th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(18);
	}),
	it("Ensures the 20th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(19);
	}),
	it("Ensures the 21th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(20);
	}),
	it("Ensures the 22th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(21);
	}),
	it("Ensures the 23th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(22);
	}),
	it("Ensures the 24th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(23);
	}),
	it("Ensures the 25th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(24);
	}),
	it("Ensures the 26th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(25);
	}),
	it("Ensures the 27th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(26);
	}),
	it("Ensures the 28th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(27);
	}),
	it("Ensures the 29th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(28);
	}),
	it("Ensures the 30th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(29);
	}),
	it("Ensures the 31th a tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('a').eq(30);
	}),
	it("Ensures the 1th ul tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('ul').eq(0)
			.should('have.css', 'margin-left', '259.828px');
	}),
	it("Ensures the 2th ul tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('ul').eq(1);
	}),
	it("Ensures the 3th ul tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('ul').eq(2);
	}),
	it("Ensures the 4th ul tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('ul').eq(3);
	}),
	it("Ensures the 1th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(0);
	}),
	it("Ensures the 2th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(1);
	}),
	it("Ensures the 3th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(2);
	}),
	it("Ensures the 4th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(3);
	}),
	it("Ensures the 5th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(4);
	}),
	it("Ensures the 6th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(5);
	}),
	it("Ensures the 7th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(6);
	}),
	it("Ensures the 8th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(7);
	}),
	it("Ensures the 9th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(8);
	}),
	it("Ensures the 10th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(9);
	}),
	it("Ensures the 11th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(10);
	}),
	it("Ensures the 12th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(11);
	}),
	it("Ensures the 13th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(12);
	}),
	it("Ensures the 14th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(13);
	}),
	it("Ensures the 15th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(14);
	}),
	it("Ensures the 16th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(15);
	}),
	it("Ensures the 17th li tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('li').eq(16);
	}),
	it("Ensures the 1th button tag matches.", () => {
		Cypress.config('defaultCommandTimeout', 1);
		cy.get('button').eq(0);
	})
})
